# Generated by Django 2.2.2 on 2019-08-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=150)),
                ('upload_file', models.FileField(upload_to='files%y%m%d')),
                ('send_to', models.EmailField(max_length=70)),
            ],
        ),
    ]
